language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3.5"

install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"

script: make test

after_success:
  coveralls
